version: '3.3'
services:
  frps:
    container_name: frps
    restart: always
    network_mode: host
    volumes:
      - '/path/to/frps.toml:/etc/frp/frps.toml'
    image: anyshpm/frps:latest
    command: frp -c /etc/frp/frps.toml

networks:
  default:
    external:
      name: "host"
