version: '3.3'
services:
  frps:
    container_name: frps
    restart: always
    network_mode: host
    volumes:
      - '/path/to/frps.ini:/etc/frp/frps.ini'
    image: anyshpm/frps
networks:
  default:
    external:
      name: "host"
